<a href="https://colab.research.google.com/github/acedesci/scanalytics/blob/master/EN/S05_Data_Preprocessing/S05_kNN_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import pandas as pd
from sklearn.impute import KNNImputer
X = pd.DataFrame([[1, 2, np.nan], [3, 4, 30], [np.nan, 6, 50], [8, 8, 70]])
X

     0  1     2
0  1.0  2   NaN
1  3.0  4  30.0
2  NaN  6  50.0
3  8.0  8  70.0

In [36]:
imputer = sklearn.impute.KNNImputer(n_neighbors=2)
X[:] = pd.DataFrame(imputer.fit_transform(X))
X

     0    1    2
0  1.0  2.0  4.0
1  3.0  4.0  3.0
2  5.5  6.0  5.0
3  8.0  8.0  7.0

In [37]:
X_normalized = pd.DataFrame()
for col in X.columns.values:
  X_normalized[col] = (X[col] - X[col].mean())/X[col].std()

X_normalized

          0         1         2
0 -1.110945 -1.161895 -0.439155
1 -0.452607 -0.387298 -1.024695
2  0.370315  0.387298  0.146385
3  1.193237  1.161895  1.317465

In [38]:
imputer = sklearn.impute.KNNImputer(n_neighbors=2)
X_normalized[:] = pd.DataFrame(imputer.fit_transform(X_normalized))
X_normalized

          0         1         2
0 -1.110945 -1.161895 -0.439155
1 -0.452607 -0.387298 -1.024695
2  0.370315  0.387298  0.146385
3  1.193237  1.161895  1.317465

In [39]:
for col in X.columns.values:
  X_normalized[col] = X_normalized[col]*X[col].std() + X[col].mean()

X_normalized

     0    1    2
0  1.0  2.0  4.0
1  3.0  4.0  3.0
2  5.5  6.0  5.0
3  8.0  8.0  7.0